// Code generated by "stringer -type=CardValue,Suit"; DO NOT EDIT

package blackjack

import "fmt"

const _CardValue_name = "JokerAceTwoThreeFourFiveSixSevenEightNineTenJackQueenKing"

var _CardValue_index = [...]uint8{0, 5, 8, 11, 16, 20, 24, 27, 32, 37, 41, 44, 48, 53, 57}

func (i CardValue) String() string {
	if i < 0 || i >= CardValue(len(_CardValue_index)-1) {
		return fmt.Sprintf("CardValue(%d)", i)
	}
	return _CardValue_name[_CardValue_index[i]:_CardValue_index[i+1]]
}

const _Suit_name = "DiamondsHeartsClubsSpades"

var _Suit_index = [...]uint8{0, 8, 14, 19, 25}

func (i Suit) String() string {
	if i < 0 || i >= Suit(len(_Suit_index)-1) {
		return fmt.Sprintf("Suit(%d)", i)
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
