// Code generated by "stringer -type=DoublingRule,SurrenderRule"; DO NOT EDIT

package blackjack

import "fmt"

const _DoublingRule_name = "DoubleOnAnyDoubleOnTenElevenDoubleOnNineTenElevenDoublingNotAllowed"

var _DoublingRule_index = [...]uint8{0, 11, 28, 49, 67}

func (i DoublingRule) String() string {
	if i < 0 || i >= DoublingRule(len(_DoublingRule_index)-1) {
		return fmt.Sprintf("DoublingRule(%d)", i)
	}
	return _DoublingRule_name[_DoublingRule_index[i]:_DoublingRule_index[i+1]]
}

const _SurrenderRule_name = "SurrenderAnySurrenderExceptDelaerAceSurrenderingNotAllowed"

var _SurrenderRule_index = [...]uint8{0, 12, 36, 58}

func (i SurrenderRule) String() string {
	if i < 0 || i >= SurrenderRule(len(_SurrenderRule_index)-1) {
		return fmt.Sprintf("SurrenderRule(%d)", i)
	}
	return _SurrenderRule_name[_SurrenderRule_index[i]:_SurrenderRule_index[i+1]]
}
