// Code generated by "stringer -type=PlayDecision"; DO NOT EDIT

package blackjack

import "fmt"

const _PlayDecision_name = "StandHitDoubleDownElseHitDoubleDownElseStandSplitElseStandSplitElseHit"

var _PlayDecision_index = [...]uint8{0, 5, 8, 25, 44, 58, 70}

func (i PlayDecision) String() string {
	if i < 0 || i >= PlayDecision(len(_PlayDecision_index)-1) {
		return fmt.Sprintf("PlayDecision(%d)", i)
	}
	return _PlayDecision_name[_PlayDecision_index[i]:_PlayDecision_index[i+1]]
}
